# ┌────────────────────────────────────────────────────────────────────┐
# │ (SSH HANDLERS)                                                     │
# │ Handlers triggered by SSH config changes.                          │
# │ - Log hardening event                                              │
# │ - Restart sshd service                                             │
# │ - Confirm restart completed                                        │
# └────────────────────────────────────────────────────────────────────┘

- name: Hardening SSH
  debug:
    msg: "Restarting SSH due to config change..."  # Notify log for traceability

- name: Restart SSH
  service:
    name: ssh       # Systemd service name for sshd
    state: restarted  # Force restart to load new config

- name: Confirm SSH
  debug:
    msg: "SSH Restarted successfully. Hardened SSH confirmed"  # Final confirmation for playbook logs
